#ifndef INSTRUCTIONDISPATCHER_H
#define INSTRUCTIONDISPATCHER_H

#include "Instruction.h"
#include <iostream>

namespace PPCVM
{
	template<typename TDispatchTo>
	class InstructionDispatcher
	{
		typedef void (TDispatchTo::*DispatchableMethod)(Instruction);
		
		static DispatchableMethod primaryTable[64];
		static DispatchableMethod table19[1024];
		static DispatchableMethod table31[1024];
		static DispatchableMethod table59[32];
		static DispatchableMethod table63[1024];
		
		static void DisassembleIfAsked(Instruction inst);
		
	public:
		void Dispatch(Instruction inst)
		{
#ifdef DEBUG_DISASSEMBLE
			void DisassembleIfAsked(Instruction inst);
			DisassembleIfAsked(inst);
#endif
			
			DispatchableMethod method = nullptr;
			switch (inst.OPCD)
			{
				case 19: method = table19[inst.SUBOP10]; break;
				case 31: method = table31[inst.SUBOP10]; break;
				case 59: method = table59[inst.SUBOP5]; break;
				case 63: method = table63[inst.SUBOP10]; break;
				default: method = primaryTable[inst.OPCD]; break;
			}
			
			TDispatchTo* target = static_cast<TDispatchTo*>(this);
			if (method == nullptr)
			{
				target->unknown(inst);
			}
			else
			{
				(target->*method)(inst);
			}
		}
	};

	template<typename TDispatchTo>
	typename InstructionDispatcher<TDispatchTo>::DispatchableMethod InstructionDispatcher<TDispatchTo>::primaryTable[64] =
	{
		[3] = &TDispatchTo::twi,
		[7] = &TDispatchTo::mulli,
		[8] = &TDispatchTo::subfic,
		[10] = &TDispatchTo::cmpli,
		[11] = &TDispatchTo::cmpi,
		[12] = &TDispatchTo::addic,
		[13] = &TDispatchTo::addic_rc,
		[14] = &TDispatchTo::addi,
		[15] = &TDispatchTo::addis,
		[16] = &TDispatchTo::bcx,
		[17] = &TDispatchTo::sc,
		[18] = &TDispatchTo::bx,
		[20] = &TDispatchTo::rlwimix,
		[21] = &TDispatchTo::rlwinmx,
		[23] = &TDispatchTo::rlwnmx,
		[24] = &TDispatchTo::ori,
		[25] = &TDispatchTo::oris,
		[26] = &TDispatchTo::xori,
		[27] = &TDispatchTo::xoris,
		[28] = &TDispatchTo::andi_rc,
		[29] = &TDispatchTo::andis_rc,
		[32] = &TDispatchTo::lwz,
		[33] = &TDispatchTo::lwzu,
		[34] = &TDispatchTo::lbz,
		[35] = &TDispatchTo::lbzu,
		[36] = &TDispatchTo::stw,
		[37] = &TDispatchTo::stwu,
		[38] = &TDispatchTo::stb,
		[39] = &TDispatchTo::stbu,
		[40] = &TDispatchTo::lhz,
		[41] = &TDispatchTo::lhzu,
		[42] = &TDispatchTo::lha,
		[43] = &TDispatchTo::lhau,
		[44] = &TDispatchTo::sth,
		[45] = &TDispatchTo::sthu,
		[46] = &TDispatchTo::lmw,
		[47] = &TDispatchTo::stmw,
		[48] = &TDispatchTo::lfs,
		[49] = &TDispatchTo::lfsu,
		[50] = &TDispatchTo::lfd,
		[51] = &TDispatchTo::lfdu,
		[52] = &TDispatchTo::stfs,
		[53] = &TDispatchTo::stfsu,
		[54] = &TDispatchTo::stfd,
		[55] = &TDispatchTo::stfdu,
	};

	template<typename TDispatchTo>
	typename InstructionDispatcher<TDispatchTo>::DispatchableMethod InstructionDispatcher<TDispatchTo>::table19[1024] =
	{
		[0] = &TDispatchTo::mcrf,
		[16] = &TDispatchTo::bclrx,
		[18] = &TDispatchTo::rfi,
		[33] = &TDispatchTo::crnor,
		[50] = &TDispatchTo::rfi,
		[129] = &TDispatchTo::crandc,
		[150] = &TDispatchTo::isync,
		[193] = &TDispatchTo::crxor,
		[225] = &TDispatchTo::crnand,
		[257] = &TDispatchTo::crand,
		[289] = &TDispatchTo::creqv,
		[417] = &TDispatchTo::crorc,
		[449] = &TDispatchTo::cror,
		[528] = &TDispatchTo::bcctrx,
	};

	template<typename TDispatchTo>
	typename InstructionDispatcher<TDispatchTo>::DispatchableMethod InstructionDispatcher<TDispatchTo>::table31[1024] =
	{
		[0] = &TDispatchTo::cmp,
		[4] = &TDispatchTo::tw,
		[8] = &TDispatchTo::subfcx,
		[10] = &TDispatchTo::addcx,
		[11] = &TDispatchTo::mulhwux,
		[19] = &TDispatchTo::mfcr,
		[20] = &TDispatchTo::lwarx,
		[23] = &TDispatchTo::lwzx,
		[24] = &TDispatchTo::slwx,
		[26] = &TDispatchTo::cntlzwx,
		[28] = &TDispatchTo::andx,
		[32] = &TDispatchTo::cmpl,
		[40] = &TDispatchTo::subfx,
		[54] = &TDispatchTo::dcbst,
		[55] = &TDispatchTo::lwzux,
		[60] = &TDispatchTo::andcx,
		[75] = &TDispatchTo::mulhwx,
		[83] = &TDispatchTo::mfmsr,
		[86] = &TDispatchTo::dcbf,
		[87] = &TDispatchTo::lbzx,
		[104] = &TDispatchTo::negx,
		[119] = &TDispatchTo::lbzux,
		[124] = &TDispatchTo::norx,
		[136] = &TDispatchTo::subfex,
		[138] = &TDispatchTo::addex,
		[144] = &TDispatchTo::mtcrf,
		[146] = &TDispatchTo::mtmsr,
		[150] = &TDispatchTo::stwcxd,
		[151] = &TDispatchTo::stwx,
		[183] = &TDispatchTo::stwux,
		[200] = &TDispatchTo::subfzex,
		[202] = &TDispatchTo::addzex,
		[210] = &TDispatchTo::mtsr,
		[215] = &TDispatchTo::stbx,
		[232] = &TDispatchTo::subfmex,
		[234] = &TDispatchTo::addmex,
		[235] = &TDispatchTo::mullwx,
		[242] = &TDispatchTo::mtsrin,
		[246] = &TDispatchTo::dcbtst,
		[247] = &TDispatchTo::stbux,
		[266] = &TDispatchTo::addx,
		[278] = &TDispatchTo::dcbt,
		[279] = &TDispatchTo::lhzx,
		[284] = &TDispatchTo::eqvx,
		[306] = &TDispatchTo::tlbie,
		[310] = &TDispatchTo::eciwx,
		[311] = &TDispatchTo::lhzux,
		[316] = &TDispatchTo::xorx,
		[339] = &TDispatchTo::mfspr,
		[343] = &TDispatchTo::lhax,
		[370] = &TDispatchTo::tlbia,
		[371] = &TDispatchTo::mftb,
		[375] = &TDispatchTo::lhaux,
		[407] = &TDispatchTo::sthx,
		[412] = &TDispatchTo::orcx,
		[438] = &TDispatchTo::ecowx,
		[439] = &TDispatchTo::sthux,
		[444] = &TDispatchTo::orx,
		[459] = &TDispatchTo::divwux,
		[467] = &TDispatchTo::mtspr,
		[470] = &TDispatchTo::dcbi,
		[476] = &TDispatchTo::nandx,
		[491] = &TDispatchTo::divwx,
		[512] = &TDispatchTo::mcrxr,
		[533] = &TDispatchTo::lswx,
		[534] = &TDispatchTo::lwbrx,
		[535] = &TDispatchTo::lfsx,
		[536] = &TDispatchTo::srwx,
		[552] = &TDispatchTo::subfx,
		[566] = &TDispatchTo::tlbsync,
		[567] = &TDispatchTo::lfsux,
		[595] = &TDispatchTo::mfsr,
		[597] = &TDispatchTo::lswi,
		[598] = &TDispatchTo::sync,
		[599] = &TDispatchTo::lfdx,
		[631] = &TDispatchTo::lfdux,
		[659] = &TDispatchTo::mfsrin,
		[661] = &TDispatchTo::stswx,
		[662] = &TDispatchTo::stwbrx,
		[663] = &TDispatchTo::stfsx,
		[695] = &TDispatchTo::stfsux,
		[725] = &TDispatchTo::stswi,
		[727] = &TDispatchTo::stfdx,
		[747] = &TDispatchTo::mullwx,
		[758] = &TDispatchTo::dcba,
		[759] = &TDispatchTo::stfdux,
		[778] = &TDispatchTo::addx,
		[790] = &TDispatchTo::lhbrx,
		[792] = &TDispatchTo::srawx,
		[824] = &TDispatchTo::srawix,
		[854] = &TDispatchTo::eieio,
		[918] = &TDispatchTo::sthbrx,
		[922] = &TDispatchTo::extshx,
		[954] = &TDispatchTo::extsbx,
		[971] = &TDispatchTo::divwux,
		[982] = &TDispatchTo::icbi,
		[983] = &TDispatchTo::stfiwx,
		[1003] = &TDispatchTo::divwx,
		[1014] = &TDispatchTo::dcbz,
	};

	template<typename TDispatchTo>
	typename InstructionDispatcher<TDispatchTo>::DispatchableMethod InstructionDispatcher<TDispatchTo>::table59[32] =
	{
		[18] = &TDispatchTo::fdivsx,
		[20] = &TDispatchTo::fsubsx,
		[21] = &TDispatchTo::faddsx,
		[24] = &TDispatchTo::fresx,
		[25] = &TDispatchTo::fmulsx,
		[28] = &TDispatchTo::fmsubsx,
		[29] = &TDispatchTo::fmaddsx,
		[30] = &TDispatchTo::fnmsubsx,
		[31] = &TDispatchTo::fnmaddsx,
	};

	template<typename TDispatchTo>
	typename InstructionDispatcher<TDispatchTo>::DispatchableMethod InstructionDispatcher<TDispatchTo>::table63[1024] =
	{
		[0] = &TDispatchTo::fcmpu,
		[12] = &TDispatchTo::frspx,
		[14] = &TDispatchTo::fctiwx,
		[15] = &TDispatchTo::fctiwzx,
		[18] = &TDispatchTo::fdivx,
		[20] = &TDispatchTo::fsubx,
		[21] = &TDispatchTo::faddx,
		[22] = &TDispatchTo::fsqrtx,
		[23] = &TDispatchTo::fselx,
		[25] = &TDispatchTo::fmulx,
		[26] = &TDispatchTo::frsqrtex,
		[28] = &TDispatchTo::fmsubx,
		[29] = &TDispatchTo::fmaddx,
		[30] = &TDispatchTo::fnmsubx,
		[31] = &TDispatchTo::fnmaddx,
		[32] = &TDispatchTo::fcmpo,
		[38] = &TDispatchTo::mtfsb1x,
		[40] = &TDispatchTo::fnegx,
		[50] = &TDispatchTo::fdivx,
		[52] = &TDispatchTo::fsubx,
		[53] = &TDispatchTo::faddx,
		[54] = &TDispatchTo::fsqrtx,
		[55] = &TDispatchTo::fselx,
		[57] = &TDispatchTo::fmulx,
		[58] = &TDispatchTo::frsqrtex,
		[60] = &TDispatchTo::fmsubx,
		[61] = &TDispatchTo::fmaddx,
		[62] = &TDispatchTo::fnmsubx,
		[63] = &TDispatchTo::fnmaddx,
		[64] = &TDispatchTo::mcrfs,
		[70] = &TDispatchTo::mtfsb0x,
		[72] = &TDispatchTo::fmrx,
		[82] = &TDispatchTo::fdivx,
		[84] = &TDispatchTo::fsubx,
		[85] = &TDispatchTo::faddx,
		[86] = &TDispatchTo::fsqrtx,
		[87] = &TDispatchTo::fselx,
		[89] = &TDispatchTo::fmulx,
		[90] = &TDispatchTo::frsqrtex,
		[92] = &TDispatchTo::fmsubx,
		[93] = &TDispatchTo::fmaddx,
		[94] = &TDispatchTo::fnmsubx,
		[95] = &TDispatchTo::fnmaddx,
		[114] = &TDispatchTo::fdivx,
		[116] = &TDispatchTo::fsubx,
		[117] = &TDispatchTo::faddx,
		[118] = &TDispatchTo::fsqrtx,
		[119] = &TDispatchTo::fselx,
		[121] = &TDispatchTo::fmulx,
		[122] = &TDispatchTo::frsqrtex,
		[124] = &TDispatchTo::fmsubx,
		[125] = &TDispatchTo::fmaddx,
		[126] = &TDispatchTo::fnmsubx,
		[127] = &TDispatchTo::fnmaddx,
		[134] = &TDispatchTo::mtfsfix,
		[136] = &TDispatchTo::fnabsx,
		[146] = &TDispatchTo::fdivx,
		[148] = &TDispatchTo::fsubx,
		[149] = &TDispatchTo::faddx,
		[150] = &TDispatchTo::fsqrtx,
		[151] = &TDispatchTo::fselx,
		[153] = &TDispatchTo::fmulx,
		[154] = &TDispatchTo::frsqrtex,
		[156] = &TDispatchTo::fmsubx,
		[157] = &TDispatchTo::fmaddx,
		[158] = &TDispatchTo::fnmsubx,
		[159] = &TDispatchTo::fnmaddx,
		[178] = &TDispatchTo::fdivx,
		[180] = &TDispatchTo::fsubx,
		[181] = &TDispatchTo::faddx,
		[182] = &TDispatchTo::fsqrtx,
		[183] = &TDispatchTo::fselx,
		[185] = &TDispatchTo::fmulx,
		[186] = &TDispatchTo::frsqrtex,
		[188] = &TDispatchTo::fmsubx,
		[189] = &TDispatchTo::fmaddx,
		[190] = &TDispatchTo::fnmsubx,
		[191] = &TDispatchTo::fnmaddx,
		[210] = &TDispatchTo::fdivx,
		[212] = &TDispatchTo::fsubx,
		[213] = &TDispatchTo::faddx,
		[214] = &TDispatchTo::fsqrtx,
		[215] = &TDispatchTo::fselx,
		[217] = &TDispatchTo::fmulx,
		[218] = &TDispatchTo::frsqrtex,
		[220] = &TDispatchTo::fmsubx,
		[221] = &TDispatchTo::fmaddx,
		[222] = &TDispatchTo::fnmsubx,
		[223] = &TDispatchTo::fnmaddx,
		[242] = &TDispatchTo::fdivx,
		[244] = &TDispatchTo::fsubx,
		[245] = &TDispatchTo::faddx,
		[246] = &TDispatchTo::fsqrtx,
		[247] = &TDispatchTo::fselx,
		[249] = &TDispatchTo::fmulx,
		[250] = &TDispatchTo::frsqrtex,
		[252] = &TDispatchTo::fmsubx,
		[253] = &TDispatchTo::fmaddx,
		[254] = &TDispatchTo::fnmsubx,
		[255] = &TDispatchTo::fnmaddx,
		[264] = &TDispatchTo::fabsx,
		[274] = &TDispatchTo::fdivx,
		[276] = &TDispatchTo::fsubx,
		[277] = &TDispatchTo::faddx,
		[278] = &TDispatchTo::fsqrtx,
		[279] = &TDispatchTo::fselx,
		[281] = &TDispatchTo::fmulx,
		[282] = &TDispatchTo::frsqrtex,
		[284] = &TDispatchTo::fmsubx,
		[285] = &TDispatchTo::fmaddx,
		[286] = &TDispatchTo::fnmsubx,
		[287] = &TDispatchTo::fnmaddx,
		[306] = &TDispatchTo::fdivx,
		[308] = &TDispatchTo::fsubx,
		[309] = &TDispatchTo::faddx,
		[310] = &TDispatchTo::fsqrtx,
		[311] = &TDispatchTo::fselx,
		[313] = &TDispatchTo::fmulx,
		[314] = &TDispatchTo::frsqrtex,
		[316] = &TDispatchTo::fmsubx,
		[317] = &TDispatchTo::fmaddx,
		[318] = &TDispatchTo::fnmsubx,
		[319] = &TDispatchTo::fnmaddx,
		[338] = &TDispatchTo::fdivx,
		[340] = &TDispatchTo::fsubx,
		[341] = &TDispatchTo::faddx,
		[342] = &TDispatchTo::fsqrtx,
		[343] = &TDispatchTo::fselx,
		[345] = &TDispatchTo::fmulx,
		[346] = &TDispatchTo::frsqrtex,
		[348] = &TDispatchTo::fmsubx,
		[349] = &TDispatchTo::fmaddx,
		[350] = &TDispatchTo::fnmsubx,
		[351] = &TDispatchTo::fnmaddx,
		[370] = &TDispatchTo::fdivx,
		[372] = &TDispatchTo::fsubx,
		[373] = &TDispatchTo::faddx,
		[374] = &TDispatchTo::fsqrtx,
		[375] = &TDispatchTo::fselx,
		[377] = &TDispatchTo::fmulx,
		[378] = &TDispatchTo::frsqrtex,
		[380] = &TDispatchTo::fmsubx,
		[381] = &TDispatchTo::fmaddx,
		[382] = &TDispatchTo::fnmsubx,
		[383] = &TDispatchTo::fnmaddx,
		[402] = &TDispatchTo::fdivx,
		[404] = &TDispatchTo::fsubx,
		[405] = &TDispatchTo::faddx,
		[406] = &TDispatchTo::fsqrtx,
		[407] = &TDispatchTo::fselx,
		[409] = &TDispatchTo::fmulx,
		[410] = &TDispatchTo::frsqrtex,
		[412] = &TDispatchTo::fmsubx,
		[413] = &TDispatchTo::fmaddx,
		[414] = &TDispatchTo::fnmsubx,
		[415] = &TDispatchTo::fnmaddx,
		[434] = &TDispatchTo::fdivx,
		[436] = &TDispatchTo::fsubx,
		[437] = &TDispatchTo::faddx,
		[438] = &TDispatchTo::fsqrtx,
		[439] = &TDispatchTo::fselx,
		[441] = &TDispatchTo::fmulx,
		[442] = &TDispatchTo::frsqrtex,
		[444] = &TDispatchTo::fmsubx,
		[445] = &TDispatchTo::fmaddx,
		[446] = &TDispatchTo::fnmsubx,
		[447] = &TDispatchTo::fnmaddx,
		[466] = &TDispatchTo::fdivx,
		[468] = &TDispatchTo::fsubx,
		[469] = &TDispatchTo::faddx,
		[470] = &TDispatchTo::fsqrtx,
		[471] = &TDispatchTo::fselx,
		[473] = &TDispatchTo::fmulx,
		[474] = &TDispatchTo::frsqrtex,
		[476] = &TDispatchTo::fmsubx,
		[477] = &TDispatchTo::fmaddx,
		[478] = &TDispatchTo::fnmsubx,
		[479] = &TDispatchTo::fnmaddx,
		[498] = &TDispatchTo::fdivx,
		[500] = &TDispatchTo::fsubx,
		[501] = &TDispatchTo::faddx,
		[502] = &TDispatchTo::fsqrtx,
		[503] = &TDispatchTo::fselx,
		[505] = &TDispatchTo::fmulx,
		[506] = &TDispatchTo::frsqrtex,
		[508] = &TDispatchTo::fmsubx,
		[509] = &TDispatchTo::fmaddx,
		[510] = &TDispatchTo::fnmsubx,
		[511] = &TDispatchTo::fnmaddx,
		[530] = &TDispatchTo::fdivx,
		[532] = &TDispatchTo::fsubx,
		[533] = &TDispatchTo::faddx,
		[534] = &TDispatchTo::fsqrtx,
		[535] = &TDispatchTo::fselx,
		[537] = &TDispatchTo::fmulx,
		[538] = &TDispatchTo::frsqrtex,
		[540] = &TDispatchTo::fmsubx,
		[541] = &TDispatchTo::fmaddx,
		[542] = &TDispatchTo::fnmsubx,
		[543] = &TDispatchTo::fnmaddx,
		[562] = &TDispatchTo::fdivx,
		[564] = &TDispatchTo::fsubx,
		[565] = &TDispatchTo::faddx,
		[566] = &TDispatchTo::fsqrtx,
		[567] = &TDispatchTo::fselx,
		[569] = &TDispatchTo::fmulx,
		[570] = &TDispatchTo::frsqrtex,
		[572] = &TDispatchTo::fmsubx,
		[573] = &TDispatchTo::fmaddx,
		[574] = &TDispatchTo::fnmsubx,
		[575] = &TDispatchTo::fnmaddx,
		[583] = &TDispatchTo::mffsx,
		[594] = &TDispatchTo::fdivx,
		[596] = &TDispatchTo::fsubx,
		[597] = &TDispatchTo::faddx,
		[598] = &TDispatchTo::fsqrtx,
		[599] = &TDispatchTo::fselx,
		[601] = &TDispatchTo::fmulx,
		[602] = &TDispatchTo::frsqrtex,
		[604] = &TDispatchTo::fmsubx,
		[605] = &TDispatchTo::fmaddx,
		[606] = &TDispatchTo::fnmsubx,
		[607] = &TDispatchTo::fnmaddx,
		[626] = &TDispatchTo::fdivx,
		[628] = &TDispatchTo::fsubx,
		[629] = &TDispatchTo::faddx,
		[630] = &TDispatchTo::fsqrtx,
		[631] = &TDispatchTo::fselx,
		[633] = &TDispatchTo::fmulx,
		[634] = &TDispatchTo::frsqrtex,
		[636] = &TDispatchTo::fmsubx,
		[637] = &TDispatchTo::fmaddx,
		[638] = &TDispatchTo::fnmsubx,
		[639] = &TDispatchTo::fnmaddx,
		[658] = &TDispatchTo::fdivx,
		[660] = &TDispatchTo::fsubx,
		[661] = &TDispatchTo::faddx,
		[662] = &TDispatchTo::fsqrtx,
		[663] = &TDispatchTo::fselx,
		[665] = &TDispatchTo::fmulx,
		[666] = &TDispatchTo::frsqrtex,
		[668] = &TDispatchTo::fmsubx,
		[669] = &TDispatchTo::fmaddx,
		[670] = &TDispatchTo::fnmsubx,
		[671] = &TDispatchTo::fnmaddx,
		[690] = &TDispatchTo::fdivx,
		[692] = &TDispatchTo::fsubx,
		[693] = &TDispatchTo::faddx,
		[694] = &TDispatchTo::fsqrtx,
		[695] = &TDispatchTo::fselx,
		[697] = &TDispatchTo::fmulx,
		[698] = &TDispatchTo::frsqrtex,
		[700] = &TDispatchTo::fmsubx,
		[701] = &TDispatchTo::fmaddx,
		[702] = &TDispatchTo::fnmsubx,
		[703] = &TDispatchTo::fnmaddx,
		[711] = &TDispatchTo::mtfsfx,
		[722] = &TDispatchTo::fdivx,
		[724] = &TDispatchTo::fsubx,
		[725] = &TDispatchTo::faddx,
		[726] = &TDispatchTo::fsqrtx,
		[727] = &TDispatchTo::fselx,
		[729] = &TDispatchTo::fmulx,
		[730] = &TDispatchTo::frsqrtex,
		[732] = &TDispatchTo::fmsubx,
		[733] = &TDispatchTo::fmaddx,
		[734] = &TDispatchTo::fnmsubx,
		[735] = &TDispatchTo::fnmaddx,
		[754] = &TDispatchTo::fdivx,
		[756] = &TDispatchTo::fsubx,
		[757] = &TDispatchTo::faddx,
		[758] = &TDispatchTo::fsqrtx,
		[759] = &TDispatchTo::fselx,
		[761] = &TDispatchTo::fmulx,
		[762] = &TDispatchTo::frsqrtex,
		[764] = &TDispatchTo::fmsubx,
		[765] = &TDispatchTo::fmaddx,
		[766] = &TDispatchTo::fnmsubx,
		[767] = &TDispatchTo::fnmaddx,
		[786] = &TDispatchTo::fdivx,
		[788] = &TDispatchTo::fsubx,
		[789] = &TDispatchTo::faddx,
		[790] = &TDispatchTo::fsqrtx,
		[791] = &TDispatchTo::fselx,
		[793] = &TDispatchTo::fmulx,
		[794] = &TDispatchTo::frsqrtex,
		[796] = &TDispatchTo::fmsubx,
		[797] = &TDispatchTo::fmaddx,
		[798] = &TDispatchTo::fnmsubx,
		[799] = &TDispatchTo::fnmaddx,
		[818] = &TDispatchTo::fdivx,
		[820] = &TDispatchTo::fsubx,
		[821] = &TDispatchTo::faddx,
		[822] = &TDispatchTo::fsqrtx,
		[823] = &TDispatchTo::fselx,
		[825] = &TDispatchTo::fmulx,
		[826] = &TDispatchTo::frsqrtex,
		[828] = &TDispatchTo::fmsubx,
		[829] = &TDispatchTo::fmaddx,
		[830] = &TDispatchTo::fnmsubx,
		[831] = &TDispatchTo::fnmaddx,
		[850] = &TDispatchTo::fdivx,
		[852] = &TDispatchTo::fsubx,
		[853] = &TDispatchTo::faddx,
		[854] = &TDispatchTo::fsqrtx,
		[855] = &TDispatchTo::fselx,
		[857] = &TDispatchTo::fmulx,
		[858] = &TDispatchTo::frsqrtex,
		[860] = &TDispatchTo::fmsubx,
		[861] = &TDispatchTo::fmaddx,
		[862] = &TDispatchTo::fnmsubx,
		[863] = &TDispatchTo::fnmaddx,
		[882] = &TDispatchTo::fdivx,
		[884] = &TDispatchTo::fsubx,
		[885] = &TDispatchTo::faddx,
		[886] = &TDispatchTo::fsqrtx,
		[887] = &TDispatchTo::fselx,
		[889] = &TDispatchTo::fmulx,
		[890] = &TDispatchTo::frsqrtex,
		[892] = &TDispatchTo::fmsubx,
		[893] = &TDispatchTo::fmaddx,
		[894] = &TDispatchTo::fnmsubx,
		[895] = &TDispatchTo::fnmaddx,
		[914] = &TDispatchTo::fdivx,
		[916] = &TDispatchTo::fsubx,
		[917] = &TDispatchTo::faddx,
		[918] = &TDispatchTo::fsqrtx,
		[919] = &TDispatchTo::fselx,
		[921] = &TDispatchTo::fmulx,
		[922] = &TDispatchTo::frsqrtex,
		[924] = &TDispatchTo::fmsubx,
		[925] = &TDispatchTo::fmaddx,
		[926] = &TDispatchTo::fnmsubx,
		[927] = &TDispatchTo::fnmaddx,
		[946] = &TDispatchTo::fdivx,
		[948] = &TDispatchTo::fsubx,
		[949] = &TDispatchTo::faddx,
		[950] = &TDispatchTo::fsqrtx,
		[951] = &TDispatchTo::fselx,
		[953] = &TDispatchTo::fmulx,
		[954] = &TDispatchTo::frsqrtex,
		[956] = &TDispatchTo::fmsubx,
		[957] = &TDispatchTo::fmaddx,
		[958] = &TDispatchTo::fnmsubx,
		[959] = &TDispatchTo::fnmaddx,
		[978] = &TDispatchTo::fdivx,
		[980] = &TDispatchTo::fsubx,
		[981] = &TDispatchTo::faddx,
		[982] = &TDispatchTo::fsqrtx,
		[983] = &TDispatchTo::fselx,
		[985] = &TDispatchTo::fmulx,
		[986] = &TDispatchTo::frsqrtex,
		[988] = &TDispatchTo::fmsubx,
		[989] = &TDispatchTo::fmaddx,
		[990] = &TDispatchTo::fnmsubx,
		[991] = &TDispatchTo::fnmaddx,
		[1010] = &TDispatchTo::fdivx,
		[1012] = &TDispatchTo::fsubx,
		[1013] = &TDispatchTo::faddx,
		[1014] = &TDispatchTo::fsqrtx,
		[1015] = &TDispatchTo::fselx,
		[1017] = &TDispatchTo::fmulx,
		[1018] = &TDispatchTo::frsqrtex,
		[1020] = &TDispatchTo::fmsubx,
		[1021] = &TDispatchTo::fmaddx,
		[1022] = &TDispatchTo::fnmsubx,
		[1023] = &TDispatchTo::fnmaddx,
	};
}

#endif