//
// MathLibFunctions.cpp
// Classix
//
// Copyright (C) 2012 Félix Cloutier
//
// This file is part of Classix.
//
// Classix is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// Classix is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
// A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// Classix. If not, see http://www.gnu.org/licenses/.
//

#include "MathLib.h"
#include "MathLibFunctions.h"

extern "C" const char* LibraryCodeSymbolNames[] = {
	"__fpclassify",
	"__fpclassifyd",
	"__fpclassifyf",
	"__inf",
	"__isfinite",
	"__isfinited",
	"__isfinitef",
	"__isnan",
	"__isnand",
	"__isnanf",
	"__isnormal",
	"__isnormald",
	"__isnormalf",
	"__signbit",
	"__signbitd",
	"__signbitf",
	"acos",
	"acosh",
	"acoshl",
	"acosl",
	"annuity",
	"asin",
	"asinh",
	"asinhl",
	"asinl",
	"atan",
	"atan2",
	"atan2l",
	"atanh",
	"atanhl",
	"atanl",
	"ceil",
	"ceill",
	"compound",
	"copysign",
	"copysignl",
	"cos",
	"cosh",
	"coshl",
	"cosl",
	"dec2f",
	"dec2l",
	"dec2num",
	"dec2numl",
	"dec2s",
	"dec2str",
	"dtox80",
	"erf",
	"erfc",
	"erfcl",
	"erfl",
	"exp",
	"exp2",
	"exp2l",
	"expl",
	"expm1",
	"expm1l",
	"fabs",
	"fabsl",
	"fdim",
	"fdiml",
	"feclearexcept",
	"fegetenv",
	"fegetexcept",
	"fegetround",
	"feholdexcept",
	"feraiseexcept",
	"fesetenv",
	"fesetexcept",
	"fesetround",
	"fetestexcept",
	"feupdateenv",
	"floor",
	"floorl",
	"fmax",
	"fmaxl",
	"fmin",
	"fminl",
	"fmod",
	"frexp",
	"frexpl",
	"gamma",
	"gammal",
	"hypot",
	"hypotl",
	"ldexp",
	"ldexpl",
	"ldtox80",
	"lgamma",
	"lgammal",
	"log",
	"log10",
	"log10l",
	"log1p",
	"log1pl",
	"log2",
	"log2l",
	"logb",
	"logbl",
	"logl",
	"modf",
	"modff",
	"modfl",
	"nan",
	"nanf",
	"nanl",
	"nearbyint",
	"nearbyintl",
	"nextafterd",
	"nextafterf",
	"nextafterl",
	"num2dec",
	"num2decl",
	"pow",
	"powl",
	"randomx",
	"relation",
	"relationl",
	"remainder",
	"remainderl",
	"remquo",
	"remquol",
	"rint",
	"rintl",
	"rinttol",
	"rinttoll",
	"round",
	"roundl",
	"roundtol",
	"roundtoll",
	"scalb",
	"scalbl",
	"sin",
	"sinh",
	"sinhl",
	"sinl",
	"sqrt",
	"sqrtl",
	"str2dec",
	"tan",
	"tanh",
	"tanhl",
	"tanl",
	"trunc",
	"truncl",
	"x80tod",
	"x80told",
	nullptr
};

extern "C" const char* LibraryDataSymbolNames[] = {
	"_FE_DFL_ENV",
	"pi",
	nullptr
};
